baseURL = 'https://www.s3-ec1-1a-01.tbc.otter.ge'
languageCode = 'en-us'
title = 'TBC | S3 Hugo'
theme = 'archie'
copyright = "© bus-hit.me"
uglyURLs = true 

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	mode="dark" # color-mode → light,dark,toggle or auto
