baseURL = 'https://www.s3-ec1-1a-01.tbc.otter.ge'
languageCode = 'en-us'
title = 'My New Hugo Sitei'
theme = 'archie'
copyright = "© bus-hit.me"
uglyURLs = true 

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
