baseURL = 'https://s3.ted.devops-ninja.me'
languageCode = 'en-us'
title = 'AWS S3'
theme = 'archie'
copyright = "© bus-hit.me"
uglyURLs = true 

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	mode="dark" # color-mode → light,dark,toggle or auto
